export const LOADER = 'LOADER'
export const CLEAR_DATA = "CLEAR_DATA"
export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const SOCIALLOGIN = "SOCIALLOGIN"
export const SOCIALLOGIN_SUCCESS = "SOCIALLOGIN_SUCCESS"
export const SOCIALLOGIN_FAILURE = "SOCIALLOGIN_FAILURE"

export const SIGNUP = "SIGNUP"
export const SIGNUP_FAILURE = "SIGNUP_FAILURE"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"

export const FORGOT_SUCCESS = "FORGOT_SUCCESS"
export const FORGOT_FAILURE = "FORGOT_FAILURE"
export const FORGOT = "FORGOT"

export const VERIFY_SUCCESS = "VERIFY_SUCCESS"
export const VERIFY_FAILURE = "VERIFY_FAILURE"
export const VERIFY = "VERIFY"

export const RESENDOTP_SUCCESS = "RESENDOTP_SUCCESS"
export const RESENDOTP_FAILURE = "RESENDOTP_FAILURE"
export const RESENDOTP = "RESENDOTP"

export const CHANGEPASSWORD_SUCCESS = "CHANGEPASSWORD_SUCCESS"
export const CHANGEPASSWORD_FAILURE = "CHANGEPASSWORD_FAILURE"
export const CHANGEPASSWORD = "CHANGEPASSWORD"

export const RESETPASSWORD_SUCCESS = "RESETPASSWORD_SUCCESS"
export const RESETPASSWORD_FAILURE = "RESETPASSWORD_FAILURE"
export const RESETPASSWORD = "RESETPASSWORD"

export const STATICCONTENT_SUCCESS = "STATICCONTENT_SUCCESS"
export const STATICCONTENT_FAILURE = "STATICCONTENT_FAILURE"
export const STATICCONTENT = "STATICCONTENT"

export const CONTACTUS_SUCCESS = "CONTACTUS_SUCCESS"
export const CONTACTUS_FAILURE = "CONTACTUS_FAILURE"
export const CONTACTUS = "CONTACTUS"

export const GETPROFILE_SUCCESS = "GETPROFILE_SUCCESS"
export const GETPROFILE_FAILURE = "GETPROFILE_FAILURE"
export const GETPROFILE = "GETPROFILE"

export const EDITPROFILE_SUCCESS = "EDITPROFILE_SUCCESS"
export const EDITPROFILE_FAILURE = "EDITPROFILE_FAILURE"
export const EDITPROFILE = "EDITPROFILE"

export const GENERATECODE_SUCCESS = "GENERATECODE_SUCCESS"
export const GENERATECODE_FAILURE = "GENERATECODE_FAILURE"
export const GENERATECODE = "GENERATECODE"

export const ADDNEWCARD_SUCCESS = "ADDNEWCARD_SUCCESS"
export const ADDNEWCARD_FAILURE = "ADDNEWCARD_FAILURE"
export const ADDNEWCARD = "ADDNEWCARD"

export const DELETEACCOUNT_SUCCESS = "DELETEACCOUNT_SUCCESS"
export const DELETEACCOUNT_FAILURE = "DELETEACCOUNT_FAILURE"
export const DELETEACCOUNT = "DELETEACCOUNT"

export const GETPAYMENTLIST_SUCCESS = "GETPAYMENTLIST_SUCCESS"
export const GETPAYMENTLIST_FAILURE = "GETPAYMENTLIST_FAILURE"
export const GETPAYMENTLIST = "GETPAYMENTLIST"

export const INVITE_SUCCESS = "INVITE_SUCCESS"
export const INVITE_FAILURE = "INVITE_FAILURE"
export const INVITE = "INVITE"

export const JOIN_SUCCESS = "JOIN_SUCCESS"
export const JOIN_FAILURE = "JOIN_FAILURE"
export const JOIN = "JOIN"

export const SAVESESSIONDETAILS_SUCCESS = "SAVESESSIONDETAILS_SUCCESS"
export const SAVESESSIONDETAILS_FAILURE = "SAVESESSIONDETAILS_FAILURE"
export const SAVESESSIONDETAILS = "SAVESESSIONDETAILS"

export const JOINMEMBER_SUCCESS = "JOINMEMBER_SUCCESS"
export const JOINMEMBER_FAILURE = "JOINMEMBER_FAILURE"
export const JOINMEMBER = "JOINMEMBER"

export const REMOVEJOINMEMBER_SUCCESS = "REMOVEJOINMEMBER_SUCCESS"
export const REMOVEJOINMEMBER_FAILURE = "REMOVEJOINMEMBER_FAILURE"
export const REMOVEJOINMEMBER = "REMOVEJOINMEMBER"

export const ADDSONG_SUCCESS = "ADDSONG_SUCCESS"
export const ADDSONG_FAILURE = "ADDSONG_FAILURE"
export const ADDSONG = "ADDSONG"

export const REMOVESONG_SUCCESS = "REMOVESONG_SUCCESS"
export const REMOVESONG_FAILURE = "REMOVESONG_FAILURE"
export const REMOVESONG = "REMOVESONG"

export const GETQUEUELIST_SUCCESS = "GETQUEUELIST_SUCCESS"
export const GETQUEUELIST_FAILURE = "GETQUEUELIST_FAILURE"
export const GETQUEUELIST = "GETQUEUELIST"

export const GETAPPLINKHISTORY_SUCCESS = "GETAPPLINKHISTORY_SUCCESS"
export const GETAPPLINKHISTORY_FAILURE = "GETAPPLINKHISTORY_FAILURE"
export const GETAPPLINKHISTORY = "GETAPPLINKHISTORY"

export const ADDMORESONG_SUCCESS = "ADDMORESONG_SUCCESS"
export const LIMIT_SUCCESS = "LIMIT_SUCCESS"
export const ADDMORESONG_FAILURE = "ADDMORESONG_FAILURE"
export const ADDMORESONG = "ADDMORESONG"

export const SAVEPLAYLIST_SUCCESS = "SAVEPLAYLIST_SUCCESS"
export const SAVEPLAYLIST_FAILURE = "SAVEPLAYLIST_FAILURE"
export const SAVEPLAYLIST = "SAVEPLAYLIST"

export const GETPLAYLIST_SUCCESS = "GETPLAYLIST_SUCCESS"
export const GETPLAYLIST_FAILURE = "GETPLAYLIST_FAILURE"
export const GETPLAYLIST = "GETPLAYLIST"

export const PAYMENTPROCESS_SUCCESS = "PAYMENTPROCESS_SUCCESS"
export const PAYMENTPROCESS_FAILURE = "PAYMENTPROCESS_FAILURE"
export const PAYMENTPROCESS = "PAYMENTPROCESS"

export const RECENTLYPLAYED_SUCCESS = "RECENTLYPLAYED_SUCCESS"
export const RECENTLYPLAYED_FAILURE = "RECENTLYPLAYED_FAILURE"
export const RECENTLYPLAYED = "RECENTLYPLAYED"

export const GETSUBSCRIPTIONLIST_SUCCESS = "GETSUBSCRIPTIONLIST_SUCCESS"
export const GETSUBSCRIPTIONLIST_FAILURE = "GETSUBSCRIPTIONLIST_FAILURE"
export const GETSUBSCRIPTIONLIST = "GETSUBSCRIPTIONLIST"

export const LINKLIBRARY_SUCCESS = "LINKLIBRARY_SUCCESS"
export const LINKLIBRARY_FAILURE = "LINKLIBRARY_FAILURE"
export const LINKLIBRARY = "LINKLIBRARY"

export const DEZEERSONGLIST_SUCCESS = "DEZEERSONGLIST_SUCCESS"
export const DEZEERSONGLIST_FAILURE = "DEZEERSONGLIST_FAILURE"
export const DEZEERSONGLIST = "DEZEERSONGLIST"