export const LOADER = 'LOADER'
export const CLEAR_DATA = "CLEAR_DATA"
export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"


export const SOCIALLOGIN = "SOCIALLOGIN"
export const SOCIALLOGIN_SUCCESS = "SOCIALLOGIN_SUCCESS"
export const SOCIALLOGIN_FAILURE = "SOCIALLOGIN_FAILURE"


export const SIGNUP = "SIGNUP"
export const SIGNUP_FAILURE = "SIGNUP_FAILURE"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"

export const FORGOT_SUCCESS = "FORGOT_SUCCESS"
export const FORGOT_FAILURE = "FORGOT_FAILURE"
export const FORGOT = "FORGOT"

export const VERIFY_SUCCESS = "VERIFY_SUCCESS"
export const VERIFY_FAILURE = "VERIFY_FAILURE"
export const VERIFY = "VERIFY"

export const RESENDOTP_SUCCESS = "RESENDOTP_SUCCESS"
export const RESENDOTP_FAILURE = "RESENDOTP_FAILURE"
export const RESENDOTP = "RESENDOTP"

export const CHANGEPASSWORD_SUCCESS = "CHANGEPASSWORD_SUCCESS"
export const CHANGEPASSWORD_FAILURE = "CHANGEPASSWORD_FAILURE"
export const CHANGEPASSWORD = "CHANGEPASSWORD"


export const RESETPASSWORD_SUCCESS = "RESETPASSWORD_SUCCESS"
export const RESETPASSWORD_FAILURE = "RESETPASSWORD_FAILURE"
export const RESETPASSWORD = "RESETPASSWORD"
